src/models.py
from . import db

class Product(db.Model):
    id          = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name        = db.Column(db.String(40), nullable=False, unique=True) 
    cbar        = db.Column(db.String(40), nullable=False, unique=True)
    qty         = db.Column(db.Integer)
    entry_price = db.Column(db.Float)
    final_price = db.Column(db.Integer)
    discript    = db.Column(db.String(180))
    category_id = db.Column(db.Integer, nullable=False)
    fabricant_id= db.Column(db.Integer)

class Category(db.Model):
    id          = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name        = db.Column(db.String(40), nullable=False, unique=True)
    discript    = db.Column(db.String(180))
    
class Order(db.Model):
    id          = db.Column(db.Integer, primary_key=True, autoincrement=True)
    ref         = db.Column(db.String(40), nullable=False, unique=True)
    products    = db.Column(db.String(40), nullable=False)
    price       = db.Column(db.Integer)

class Fabricant(db.Model):
    id          = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name        = db.Column(db.String(40), nullable=False, unique=True)

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = "ALPSOODKEdkhfds4d5s6f4dsf"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db/db.sql'
    db.init_app(app)

    from .views import views
    app.register_blueprint(views)
    from .models import Product, Category
    return app

src/views.py
from flask import Blueprint, jsonify, redirect, request, render_template, url_for
from uuid import uuid4

from sqlalchemy import false
from .commit_get import *

views = Blueprint("views", __name__)

@views.route("/")
def index():
    return render_template("index.html", fact_id=str(uuid4()), title="LFDSS", home="active")

@views.route("/insertion", methods=["POST", "GET"])
def insertion():
    if request.method == "GET":
        return render_template("insertion.html", title="LFDSS",
                               ins="active", cat=get_db("category", ["all"]),
                               fab=get_db("fabricant", ["all"]))

@views.route("/ravitaillement", methods=["POST", "GET"])
def rav():
    return render_template("rav.html", rav="active")

@views.route("/stock", methods=["POST", "GET"])
def stock():
    cat = get_cat()
    fab = get_fab()
    if request.method=="GET":
        product_list = get_db("produit", ["all"])
        parsed  = [{"name":i.name, 
                    "fab":get_by_id("fabricant", i.fabricant_id), 
                    "category":get_by_id("category", i.category_id), 
                    "cbar":i.cbar, "prix":i.final_price, "qty":i.qty} for i in product_list]
        
        return render_template("stock.html", stock="active", product=parsed, category_list=cat, fabricant_list=fab)
    else: 
        category = request.form.get("category")
        fabricant= request.form.get("fabricant")
        if not category and not fabricant:
            return redirect(url_for("views.stock"))
        elif category and fabricant:
            product_list = get_product_by_cat_fab(int(fabricant), int(category))
            parsed  = [{"name":i.name, 
                    "fab":get_by_id("fabricant", i.fabricant_id), 
                    "category":get_by_id("category", i.category_id), 
                    "cbar":i.cbar, "prix":i.final_price, "qty":i.qty} for i in product_list]
            return render_template("stock.html", stock="active", product=parsed, category_list=cat, fabricant_list=fab)
        elif fabricant:
            product_list = get_product_by_fab(int(fabricant))
            parsed  = [{"name":i.name, 
                    "fab":get_by_id("fabricant", i.fabricant_id), 
                    "category":get_by_id("category", i.category_id), 
                    "cbar":i.cbar, "prix":i.final_price, "qty":i.qty} for i in product_list]
            return render_template("stock.html", stock="active", product=parsed, category_list=cat, fabricant_list=fab)
        elif category:
            product_list = get_product_by_cat(int(category))
            parsed  = [{"name":i.name, 
                    "fab":get_by_id("fabricant", i.fabricant_id), 
                    "category":get_by_id("category", i.category_id), 
                    "cbar":i.cbar, "prix":i.final_price, "qty":i.qty} for i in product_list]
            return render_template("stock.html", stock="active", product=parsed, category_list=cat, fabricant_list=fab)

        

        return render_template("stock.html", stock="active", product=parsed, category_list=cat, fabricant_list=fab)


@views.route("/finance", methods=["POST", "GET"])
def finance():
    return render_template("finance.html", finance="active")

@views.route("/add/<element>", methods=["POST"])
def add(element):
    if request.method == "POST":
       
        if element == "product":
            name = request.form.get("name")
            c_bar= request.form.get("c_bar")
            qty  = request.form.get("qty")
            entry_price  = request.form.get("entry_price") 
            final_price  = request.form.get("final_price") 
            discript = request.form.get("discript") 
            category = request.form.get("category")
            fabricant= request.form.get("fabricant")
            
            c = get_db("category", [category])
            f = get_db("fabricant", [fabricant])
            
            print(entry_price)
            commit = commit_db("product", [name, c_bar, qty, entry_price, final_price, discript, c, f ])
            return redirect(url_for('views.insertion'))

        elif element == "category":
            name = request.form.get("name")
            discript  = request.form.get("discript")
            commit = commit_db("category", [name, discript])
            return redirect(url_for('views.insertion'))
        
        elif element == "fabricant":
            name = request.form.get("name")
            
            commit = commit_db("fabricant", [name])
            return redirect(url_for('views.insertion'))

    return redirect(url_for('views.index'))

@views.route("/get", methods=["POST"])
def get_item():
    rep = request.json
    if "c_bar" in rep.keys():
        product = get_product_by_cbar(rep["c_bar"])
        if product:
            data = {"name": product.name, "prix": product.final_price}
            return jsonify(data)
    return jsonify({"error":"True"})

@views.route("/order", methods=['POST'])
def order():
    data = request.json
    if "product" in data.keys():
        product = data["product"]
        if len(product):
            st_set = set_db(product)
            if st_set:
                st_commit = commit_db("order", [data["or_id"], data["order_price"], str(data["product"])])
                return jsonify({"error":"False"})

    return jsonify({"error":"True"})

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{{ titel }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/offcanvas-navbar/">
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    

    <!-- Bootstrap core CSS -->
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/features.css') }}" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
  </head>
<body class="bg-light"> 
<nav class="navbar navbar-expand navbar-dark bg-dark" aria-label="Second navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">LFDSS</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {{ home }}" aria-current="page" href="{{ url_for('views.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ ins }}" href="{{ url_for('views.insertion') }}">Insertion</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ rav }}" href="{{ url_for('views.rav') }}">Ravitaillement</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ stock }}" href="{{ url_for('views.stock') }}">Stock</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {{ finance }}" href="{{ url_for('views.finance') }}">Finance</a>
          </li>
        </ul>
        <form>
          <input class="form-control" type="text" placeholder="Search" aria-label="Search">
        </form>
      </div>
    </div>
  </nav>
{% block main %}

{% endblock %}
</body>
</html>

src/templates/finance.html
{% extends 'base.html' %}

{% block main %}  

<div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>
    <div class="col-10 themed-grid-col">
      <hr class="my-4">
      <div class="col-md-7 col-lg-12">
          <h4 class="mb-3">Produits</h4>
            <div class="row g-3">
              
              <div class="col-md-4">
                <label for="country" class="form-label">Finance</label>
                <select class="form-select" name="fabricant"required="">
                  <option value="">Choisissez...</option>
                  {% for i in fabricant_list %}
                  <option value="{{ i['id'] }}">{{ i['name'] }}</option>
                  {% endfor %}
                </select>
              </div>
      
              <div class="col-md-4">
                <label for="state" class="form-label">Categorie</label>
                <select class="form-select" name="category" required="">
                  <option value="">Choisissez...</option>
                  {% for y in category_list %}
                  <option value="{{ y['id'] }}"> {{ y['name'] }}</option>
                  {% endfor %}
                </select>
              </div>
              
              <div class="col-md-4">
                <label for="country" class="form-label"><br></label>
              <button class=" w-100 btn btn-primary " type="submit">Filtrer Les Produits</button>
            </div>
    
            </div>
      
            <hr class="my-4">

        </div>
      

  </div>
    <div class="col-1 themed-grid-col"></div>
  </div>
  <div class="b-example-divider"></div>

  <div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>


    <div class="col-10 themed-grid-col">
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">Produit</th>
            <th scope="col">Fabriquant</th>
            <th scope="col">Categorie</th>
            <th scope="col">Code barre</th>
            <th scope="col">Prix</th>
            <th scope="col">Quantité</th>
          </tr>
          </thead>
          <tbody>
            {% for ord in orders %}
          <tr>
            <th>{{ ord['name'] }}</th>
            <td>{{ ord['fab'] }}</td>
          </tr>
            {% endfor %}
          </tbody>
        </table>

        <div class="col-md-7 col-lg-12"></div>
    </div>
    <div class="col-1 themed-grid-col"></div>
  </div>

{% endblock %}

src/templates/index.html
{% extends 'base.html' %}
{% block main %}
<div class="w-100 p-3">



    <div class="bd-example" id="cbar_flash">
        <form onsubmit="return false" class="row g-3">
          <div class="col-sm-6">
            <label for="validationServer01" class="form-label">Numero de Facture</label>
            <input type="text" class="form-control" id="fact_id" value="{{ fact_id }}" required="">
          </div>
          <div class="col-sm-6" >
            <label for="validationServer02" class="form-label">Code Barre</label>
            <input type="text" class="form-control" id="c_bar_product" required="" autofocus>
          </div>
          <div class="invisible col-sm-6">
            <button class="" onclick="get_product()" type="submit">Ajouter</button>
          </div>
        </form>
    </div>

  <script>

  function getKeyByValue(object, value) {
    return Object.keys(object).find(key => object[key] === value);
  }
    function get_product(){
    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/get", true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify({
        c_bar: document.getElementById("c_bar_product").value,
        or_id: document.getElementById("fact_id").value
    }));

    document.getElementById("c_bar_product").value = "";
    xhr.onload = function() {
      console.log(this.responseText);
      var data = JSON.parse(this.responseText);
      var table = document.getElementById("product_table");
      var total_out = document.getElementById("total_price");
      var total = 0;
      var table_val = {};
      if (data["error"]=="True"){
        var flash_error = document.getElementById("cbar_flash")
        flash_error.innerHTML += '<div class="alert alert-danger alert-dismissible fade show" role="alert"> Code Barre non enregistre <a href="/insertion" class="alert-link">Ajouter le Prodiuit ICI</a>.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> </div>'
      }
      else{
      for (var i = 0, row; row=table.rows[i]; i++){
        table_val[i] = row.cells[0].innerText;
      }

      if (Object.values(table_val).includes(data["name"])){
        var k = getKeyByValue(table_val,data["name"]);
        table.rows[k].cells[1].innerHTML = parseInt(table.rows[k].cells[1].innerText) + 1;
        table.rows[k].cells[3].innerHTML = parseInt(table.rows[k].cells[2].innerText) * parseInt(table.rows[k].cells[1].innerText);
      }
      else{
        var row = table.insertRow(1);
        var cell1 = row.insertCell(0);
        var cell2 = row.insertCell(1);
        var cell3 = row.insertCell(2);
        var cell4 = row.insertCell(3);
        cell1.innerHTML = data["name"];
        cell2.innerHTML = "1";
        cell3.innerHTML = data["prix"];
        cell4.innerHTML = data["prix"];
      }
      for (var i = 1, row; row=table.rows[i]; i++){
        total = total + parseInt(row.cells[3].innerText);
      }
      total_out.innerHTML = total;

    }}
  }

  function post_order(){
    var table = document.getElementById("product_table");
    var order_uid = document.getElementById("fact_id").value;
    var total = document.getElementById("total_price").innerText;
    var table_val = {};

    for (var i = 1, row; row=table.rows[i]; i++){
        table_val[row.cells[0].innerText] = row.cells[1].innerText;
      }

    var xhr = new XMLHttpRequest();
    xhr.open("POST", "/order", true);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify({
        or_id: order_uid,
        order_price: total,
        product: table_val
    }));

    document.getElementById("c_bar_product").value = "";
    xhr.onload = function() {
      console.log(this.responseText);
      var data = JSON.parse(this.responseText);
      
      if (data["error"]=="True"){
        var flash_error = document.getElementById("stock_flash")
        flash_error.innerHTML += '<div class="alert alert-danger alert-dismissible fade show" role="alert">Erreur Stock<a href="/insertion" class="alert-link">Ravitailler ICI</a>.<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> </div>'
      }
      else{
        location.reload();
      }}
    }
    
    </script>
</div> 


<div class="b-example-divider"></div>
<div> 
<table class="table table-sm table-bordered" id="product_table">
    <tr>
      <th scope="col">Produits</th>
      <th scope="col">Quantité</th>
      <th scope="col">Pix Unitaire</th>
      <th scope="col">Prix Total</th>
    </tr>
  </table>
</div>
<div class="b-example-divider"></div>
<div class="row mb-3">
  <div class="col-md-7 themed-grid-col"><br><button onclick="post_order()" class="w-100 btn btn-primary btn-lg">Valider l'achat</button></div>
  <div class="col-md-2 themed-grid-col"><br><h2>Prix Total:</h2></div>
  <div class="col-md-2 themed-grid-col"><br><h3 id="total_price">00.00</h3></div>
  <div class="col-md-1 themed-grid-col"><br><h3 >DZD</h3></div>
  <div class="col-md-12 themed-grid-col" id="stock_flash"></div>
</div>
<div class="b-example-divider"></div>
{% endblock %}

src/templates/insertion.html
{% extends 'base.html' %}

{% block main %}  


<div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>
    <div class="col-10 themed-grid-col">
        <hr class="my-4">
        <div class="col-md-7 col-lg-12">
            <h4 class="mb-3">Nouveau Produit</h4>
            <form action="/add/product" method="POST" class="needs-validation" novalidate="">
              <div class="row g-3">
                <div class="col-sm-6">
                  <label for="firstName" class="form-label">Nom du produit</label>
                  <input type="text" class="form-control" name="name" id="firstName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Nom du produit est obligatoir.
                  </div>
                </div>
        
                <div class="col-sm-6">
                  <label for="lastName" class="form-label">Code Barre</label>
                  <input type="text" class="form-control" name="c_bar" id="lastName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Le code barre du produit est obligatoir.
                  </div>
                </div>
        
                <div class="col-12">
                  <label for="username" class="form-label">Dscription</label>
                  <div class="input-group has-validation">
                    <span class="input-group-text">@</span>
                    <input type="text" class="form-control" name="discript" id="username" placeholder="Dscription breve du produit" required="">
                  </div>
                </div>
        
                <div class="col-md-3">
                  <label for="country" class="form-label">Fabricant</label>
                  <select class="form-select" name="fabricant" id="country" required="">
                    <option value="">Choisissez...</option>
                    {% for i in fab %}
                    <option>{{i}}</option>
                    {% endfor %}
                  </select>
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
        
                <div class="col-md-3">
                  <label for="state" class="form-label">Categorie</label>
                  <select class="form-select" name="category" id="state" required="">
                    <option value="">Choisissez...</option>
                    {% for i in cat %}
                    <option>{{ i }}</option>
                    {% endfor %}
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>
                </div>
        
                <div class="col-md-2">
                  <label for="zip" class="form-label">Quantité</label>
                  <input type="text" name="qty" class="form-control" id="zip" placeholder="" required="">
                  <div class="invalid-feedback">
                    La quantité est requise.
                  </div>
                </div>

                <div class="col-md-2">
                    <label for="zip"  class="form-label">Prix de gors</label>
                    <input type="text" name="entry_price" class="form-control" id="zip" placeholder="DZD" required="">
                    <div class="invalid-feedback">
                      Le prix de gros requis.
                    </div>
                  </div>

                  <div class="col-md-2">
                    <label for="zip" class="form-label">Prix Unitaire</label>
                    <input type="text" name="final_price" class="form-control" id="zip" placeholder="DZD" required="">
                    <div class="invalid-feedback">
                      Le prix unitaire est requis.
                    </div>
                  </div>
              </div>
        
              <hr class="my-4">
              <button class="w-100 btn btn-primary btn-lg" type="submit">Ajouter Le Produit</button>
              
            </form>
          </div>
        

    </div>
    <div class="col-1 themed-grid-col"></div>
  </div>
  <div class="b-example-divider"></div>

  <div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>


    <div class="col-10 themed-grid-col">
        <hr class="my-4">
        <div class="col-md-7 col-lg-12">
            <h4 class="mb-3">Nouvelle Categorie</h4>
            <form action="/add/category" method="POST" class="needs-validation" novalidate="">
              <div class="row g-3">
                <div class="col-sm-6">
                  <label for="firstName" class="form-label">Nom de la Categorie</label>
                  <input type="text" name="name" class="form-control" id="firstName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Nom de la Categorie est obligatoir.
                  </div>
                </div>
        
        
                <div class="col-6">
                  <label for="username" class="form-label">Dscription</label>
                  <div class="input-group has-validation">
                    <span class="input-group-text">@</span>
                    <input type="text" name="discript" class="form-control" id="username" placeholder="Dscription breve de la Categorie" required="">
                  </div>
                </div>
        
              
              <button class="w-100 btn btn-primary btn-lg" type="submit">Ajouter La Categorie</button>
              
            </form>
            <hr class="my-4">
          </div>


          <div class="col-md-7 col-lg-12">
            <h4 class="mb-3">Nouveau Fabricant</h4>
            <form action="/add/fabricant" method="POST" class="needs-validation" novalidate="">
              <div class="row g-3">
                <div class="col-sm-12">
                  <label for="firstName" class="form-label">Nom de la Marque</label>
                  <input type="text" name="name" class="form-control" id="firstName" placeholder="" value="" required="">
                  <div class="invalid-feedback">
                    Nom de la Categorie est obligatoir.
                  </div>
                </div>
              <button class="w-100 btn btn-primary btn-lg" type="submit">Ajouter Le Fabricant</button>
              
            </form>
            <hr class="my-4">
          </div>
    </div>

    
    


    <div class="col-1 themed-grid-col"></div>
  </div>

{% endblock %}

src/templates/rav.html
{% extends 'base.html' %}

{% block main %} 


{% endblock %}

src/templates/stock.html
{% extends 'base.html' %}

{% block main %}  

<div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>
    <div class="col-10 themed-grid-col">
      <hr class="my-4">
      <div class="col-md-7 col-lg-12">
          <h4 class="mb-3">Produits</h4>
          <form action="/stock" method="POST" class="needs-validation" novalidate="">
            <div class="row g-3">
              
              <div class="col-md-4">
                <label for="country" class="form-label">Fabricant</label>
                <select class="form-select" name="fabricant"required="">
                  <option value="">Choisissez...</option>
                  {% for i in fabricant_list %}
                  <option value="{{ i['id'] }}">{{ i['name'] }}</option>
                  {% endfor %}
                </select>
              </div>
      
              <div class="col-md-4">
                <label for="state" class="form-label">Categorie</label>
                <select class="form-select" name="category" required="">
                  <option value="">Choisissez...</option>
                  {% for y in category_list %}
                  <option value="{{ y['id'] }}"> {{ y['name'] }}</option>
                  {% endfor %}
                </select>
              </div>
              
              <div class="col-md-4">
                <label for="country" class="form-label"><br></label>
              <button class=" w-100 btn btn-primary " type="submit">Filtrer Les Produits</button>
            </div>
    
            </div>
      
            <hr class="my-4">
            
          </form>
        </div>
      

  </div>
    <div class="col-1 themed-grid-col"></div>
  </div>
  <div class="b-example-divider"></div>

  <div class="row mb-3">
    <div class="col-1 themed-grid-col"></div>


    <div class="col-10 themed-grid-col">
        <table class="table table-striped">
          <thead>
          <tr>
            <th scope="col">Produit</th>
            <th scope="col">Fabriquant</th>
            <th scope="col">Categorie</th>
            <th scope="col">Code barre</th>
            <th scope="col">Prix</th>
            <th scope="col">Quantité</th>
          </tr>
          </thead>
          <tbody>
            {% for prod in product %}
          <tr>
            <th>{{ prod['name'] }}</th>
            <td>{{ prod['fab'] }}</td>
            <td>{{ prod['category'] }}</td>
            <td>{{ prod['cbar'] }}</td>
            <td>{{ prod['prix'] }}</td>
            <td>{{ prod['qty'] }}</td>
          </tr>
            {% endfor %}
          </tbody>
        </table>

        <div class="col-md-7 col-lg-12"></div>
    </div>
    <div class="col-1 themed-grid-col"></div>
  </div>

{% endblock %}